pluginManagement {
    buildscript {
        repositories { mavenCentral() }
        dependencies { classpath 'com.google.code.gson:gson:2.10.1' }
    }
    repositories {
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases'
        }
        maven {
            name = 'Parchment'
            url = 'https://maven.parchmentmc.org'
        }
        maven {
            name = 'FabricMC'
            url = 'https://maven.fabricmc.net/'
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.5.0'
}

rootProject.name = 'ssrcamerafixes'

include 'forge'
include 'fabric'
include 'neoforge'
include 'fabric-1211'
include 'forge-1.19.2'
