plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.78'
}

version = neoforge_mod_version
group = mod_group_id

base {
    archivesName = "${mod_id}-neoforge-${neoforge_mc_version}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neoforge_version

    parchment {
        mappingsVersion = project.neoforge_parchment_version
        minecraftVersion = project.neoforge_parchment_mc
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    maven { url "https://cursemaven.com" }
    maven { url "https://maven.parchmentmc.org" }
}

dependencies {
    compileOnly "curse.maven:shoulder-surfing-reloaded-243190:8301658"
    compileOnly "curse.maven:epic-fight-mod-405076:8080214"
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: neoforge_mc_version,
            minecraft_version_range: neoforge_mc_version_range,
            neoforge_version: neoforge_version,
            neoforge_version_range: neoforge_version_range,
            loader_version_range: neoforge_loader_version_range,
            mod_id: mod_id, mod_name: mod_name, mod_license: mod_license,
            mod_version: neoforge_mod_version,
            mod_authors: mod_authors, mod_description: neoforge_mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : '1',
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
        ])
    }
}

tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
